language: python
python: 3.9
install:
  - pip3 install -r requirements-ci.txt
  - pip3 install -r requirements.txt
stages:
  - static code analysis
jobs:
  include:
    - stage: static code analysis
      name: codestyle
      script: python3 -m pycodestyle .
    - stage: static code analysis
      name: lint
      script: python3 -m pylint --rcfile=.pylintrc record.py
